//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatWebsiteProjectCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.messages = new HashSet<message>();
            this.messages1 = new HashSet<message>();
            this.notifies = new HashSet<notify>();
            this.relationships = new HashSet<relationship>();
            this.relationships1 = new HashSet<relationship>();
        }
    
        public System.Guid app_user_id { get; set; }
        public string avatar { get; set; }
        public string fullname { get; set; }
        public bool status_online { get; set; }
        public System.DateTimeOffset last_online { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public bool gender { get; set; }
        public System.DateTime birth { get; set; }
        public string city { get; set; }
        public string customer_description { get; set; }
    
        public virtual app_user app_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message> messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message> messages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notify> notifies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<relationship> relationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<relationship> relationships1 { get; set; }
    }
}
