//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class relationship
    {
        public string relationship_id { get; set; }
        public string cus1_id { get; set; }
        public string cus2_id { get; set; }
        public int relationship_status { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual customer customer1 { get; set; }
    }
}
